from __future__ import annotations

import html
import re
from datetime import datetime
from typing import Any
from urllib.parse import unquote

import requests

from .config import (
    TRELLO_API_KEY,
    TRELLO_API_TOKEN,
    TRELLO_BOARD_ID,
    REPORT_TRELLO_LIST_IDS,
)


def normalize_person_name(value: Any) -> str:
    if not value:
        return ""
    text = re.sub(r"[–—−]", "-", str(value))
    text = re.sub(r"[^\w\s']", " ", text, flags=re.UNICODE)
    text = re.sub(r"\s+", " ", text)
    return text.strip().lower()


def normalize_phone(value: Any) -> str:
    digits = re.sub(r"\D", "", str(value or ""))
    if not digits:
        return ""
    if digits.startswith("00"):
        digits = digits[2:]
    if digits.startswith("07") and len(digits) == 11:
        digits = "44" + digits[1:]
    elif len(digits) == 10 and digits.startswith("7"):
        digits = "44" + digits
    elif digits.startswith("0") and len(digits) == 11:
        digits = "44" + digits[1:]
    if len(digits) < 8 or len(digits) > 15:
        return ""
    return digits


def parse_card_identity(card_name: str) -> tuple[str, str]:
    """Return (full_name, normal_phone) from the standard SPRING card title."""
    text = str(card_name or "").strip()
    if not text:
        return "", ""

    match = re.search(
        r"Phone\s*:\s*(\+?\d[\d\s().-]{7,}\d)",
        text,
        flags=re.IGNORECASE,
    )
    if match:
        fullname = text[: match.start()].strip()
        fullname = re.sub(r"\s*[–—-]\s*$", "", fullname).strip()
        return fullname, normalize_phone(match.group(1))

    return text, ""


def extract_whatsapp_phone_from_description(description: str) -> str:
    text = str(description or "")
    patterns = (
        r"https?://(?:www\.)?wa\.me/(\+?\d+)",
        r"https?://web\.whatsapp\.com/send\?[^\n\r<>\"']*?(?:^|[?&])phone=(\+?\d+)",
    )
    for pattern in patterns:
        match = re.search(pattern, text, flags=re.IGNORECASE)
        if match:
            phone = normalize_phone(match.group(1))
            if phone:
                return phone
    return ""


def parse_outlook_comment(comment_text: str) -> dict[str, Any] | None:
    """Parse an Outlook comment generated by the Power Automate backfill/live flow."""
    text = html.unescape(str(comment_text or ""))
    if not text.startswith("📧⬇️ **Incoming Outlook**") and not text.startswith(
        "📧⬆️ **Outgoing Outlook**"
    ):
        return None

    direction = "incoming" if text.startswith("📧⬇️") else "outgoing"
    date_match = re.search(r"Outlook\*\*\s*\((\d{2}-\d{2}-\d{4})\)", text)
    event_date = None
    if date_match:
        try:
            event_date = datetime.strptime(date_match.group(1), "%d-%m-%Y")
        except ValueError:
            event_date = None

    person_match = re.search(r"\n(?:From|To):\s*\*\*(.*?)\*\*", text, flags=re.DOTALL)
    subject_match = re.search(r"\nSubject:\s*\*\*(.*?)\*\*", text, flags=re.DOTALL)
    view_match = re.search(r"\[View message\]\(([^)]+)\)", text, flags=re.DOTALL)

    person = person_match.group(1).strip() if person_match else ""
    subject = subject_match.group(1).strip() if subject_match else ""
    view_url = view_match.group(1).strip() if view_match else ""

    message_id = ""
    id_match = re.search(r"[?&]ItemID=([^&)]*)", view_url)
    if id_match:
        message_id = unquote(id_match.group(1))

    return {
        "direction": direction,
        "event_date": event_date,
        "person": person,
        "subject": subject,
        "view_url": view_url,
        "message_id": message_id,
        "raw_text": text,
    }



def classify_trello_comment(comment_text: str) -> str:
    text = str(comment_text or "").strip()
    outlook = parse_outlook_comment(text)
    if outlook:
        return "outlook"

    # Current WhatsApp → Trello format: **Spring3 (From|To: phone) — date**
    if re.match(
        r"^\*\*.*?\((?:From|To):\s*[^)]+\)(?:\s*—\s*[^*]+)?\*\*",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    ):
        return "whatsapp"

    # Legacy WhatsApp format: WhatsApp message (...) FROM|TO ...:
    if re.match(
        r"^WhatsApp message \(.+?\)\s+(?:FROM|TO)\s+[^:]+:",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    ):
        return "whatsapp"

    return "trello"

def _parse_trello_datetime(value: Any) -> datetime | None:
    if not value:
        return None
    text = str(value).replace("Z", "+00:00")
    try:
        return datetime.fromisoformat(text)
    except ValueError:
        return None


class TrelloClient:
    def __init__(self) -> None:
        if not TRELLO_API_KEY or not TRELLO_API_TOKEN:
            raise RuntimeError(
                "Trello reporting requires TRELLO_API_KEY and TRELLO_API_TOKEN."
            )
        if not TRELLO_BOARD_ID:
            raise RuntimeError("Trello reporting requires TRELLO_BOARD_ID.")

    @property
    def available(self) -> bool:
        return bool(TRELLO_API_KEY and TRELLO_API_TOKEN and TRELLO_BOARD_ID)

    def request(self, method: str, endpoint: str, params: dict[str, Any] | None = None) -> Any:
        params = dict(params or {})
        params["key"] = TRELLO_API_KEY
        params["token"] = TRELLO_API_TOKEN
        response = requests.request(
            method,
            f"https://api.trello.com/1{endpoint}",
            params=params,
            timeout=60,
        )
        response.raise_for_status()
        return response.json() if response.text else {}

    def list_cards(self) -> list[dict[str, Any]]:
        fields = "id,name,idList,closed,desc,labels,dateLastActivity,shortLink,url"
        list_ids = [x.strip() for x in REPORT_TRELLO_LIST_IDS.split(",") if x.strip()]
        if list_ids:
            cards: list[dict[str, Any]] = []
            seen: set[str] = set()
            for list_id in list_ids:
                rows = self.request(
                    "GET",
                    f"/lists/{list_id}/cards",
                    {"fields": fields, "limit": 1000},
                )
                for card in rows or []:
                    if card.get("id") not in seen:
                        seen.add(card.get("id"))
                        cards.append(card)
            return cards

        return self.request(
            "GET",
            f"/boards/{TRELLO_BOARD_ID}/cards",
            {"fields": fields, "limit": 1000},
        )

    def list_card_comments(self, card_id: str, page_limit: int = 100) -> list[dict[str, Any]]:
        comments: list[dict[str, Any]] = []
        before: str | None = None
        while True:
            params: dict[str, Any] = {
                "filter": "commentCard",
                "limit": min(page_limit, 100),
                "fields": "id,data,date,type",
            }
            if before:
                params["before"] = before
            rows = self.request("GET", f"/cards/{card_id}/actions", params)
            rows = rows or []
            comments.extend(rows)
            if len(rows) < min(page_limit, 100):
                break
            last_id = rows[-1].get("id")
            if not last_id or last_id == before:
                break
            before = last_id
        return comments

    @staticmethod
    def parse_card_metadata(card: dict[str, Any]) -> dict[str, Any]:
        fullname, phone = parse_card_identity(card.get("name", ""))
        wa_phone = extract_whatsapp_phone_from_description(card.get("desc", ""))
        return {
            "card_id": card.get("id", ""),
            "fullname": fullname,
            "phone": phone,
            "whatsapp_phone": wa_phone,
            "name": card.get("name", ""),
            "id_list": card.get("idList", ""),
            "closed": bool(card.get("closed")),
            "labels_json": card.get("labels", []) or [],
            "short_link": card.get("shortLink", ""),
            "url": card.get("url", ""),
            "date_last_activity": _parse_trello_datetime(card.get("dateLastActivity")),
        }
